## Food Waste Management Analysis

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("food_waste.csv")
print(df)

                        Country  combined figures (kg/capita/year)  \
0                   Afghanistan                                126
1                       Albania                                127
2                       Algeria                                135
3                       Andorra                                123
4                        Angola                                144
..                          ...                                ...
209  Venezuela (Boliv. Rep. of)                                116
210                    Viet Nam                                120
211                       Yemen                                148
212                      Zambia                                122
213                    Zimbabwe                                144

     Household estimate (kg/capita/year)  Household estimate (tonnes/year)  \
0                                     82                           3109153
1                                     83                            238492
2                                     91                           3918529
3                                     84                              6497
4                                    100                           3169523
..                                   ...                               ...
209                                   72                           2065461
210                                   76                           7346717
211                                  104                           3026946
212                                   78                           1391729
213                                  100                           1458564

     Retail estimate (kg/capita/year)  Retail estimate (tonnes/year)  \
0                                  16                         594982
1                                  16                          45058
2                                  16                         673360
3                                  13                            988
4                                  16                         497755
..                                ...                            ...
209                                16                         445994
210                                16                        1508689
211                                16                         456099
212                                16                         279350
213                                16                         229059

     Food service estimate (kg/capita/year)  \
0                                        28
1                                        28
2                                        28
3                                        26
4                                        28
..                                      ...
209                                      28
210                                      28
211                                      28
212                                      28
213                                      28

     Food service estimate (tonnes/year) Confidence in estimate  M49 code  \
0                                1051783    Very Low Confidence         4
1                                  79651    Very Low Confidence         8
2                                1190335    Very Low Confidence        12
3                                   1971         Low Confidence        20
4                                 879908    Very Low Confidence        24
..                                   ...                    ...       ...
209                               788407    Very Low Confidence       862
210                              2666991    Very Low Confidence       704
211                               806270    Very Low Confidence       887
212                               493822    Very Low Confidence       894
213                               404920    Very Low Confidence       716

                              Region  \
0                      Southern Asia
1                    Southern Europe
2                    Northern Africa
3                    Southern Europe
4                 Sub-Saharan Africa
..                               ...
209  Latin America and the Caribbean
210               South-eastern Asia
211                     Western Asia
212               Sub-Saharan Africa
213               Sub-Saharan Africa

                                                Source
0    https://www.unep.org/resources/report/unep-foo...
1    https://www.unep.org/resources/report/unep-foo...
2    https://www.unep.org/resources/report/unep-foo...
3    https://www.unep.org/resources/report/unep-foo...
4    https://www.unep.org/resources/report/unep-foo...
..                                                 ...
209  https://www.unep.org/resources/report/unep-foo...
210  https://www.unep.org/resources/report/unep-foo...
211  https://www.unep.org/resources/report/unep-foo...
212  https://www.unep.org/resources/report/unep-foo...
213  https://www.unep.org/resources/report/unep-foo...

[214 rows x 12 columns]

In [5]:
df.describe()

,combined figures (kg/capita/year),Household estimate (kg/capita/year),Household estimate (tonnes/year),Retail estimate (kg/capita/year),Retail estimate (tonnes/year),Food service estimate (kg/capita/year),Food service estimate (tonnes/year),M49 code
count,214.000000,214.000000,2.140000e+02,214.000000,2.140000e+02,214.000000,2.140000e+02,214.000000
mean,126.794393,84.294393,2.658896e+06,15.116822,5.520454e+05,27.383178,1.138859e+06,433.971963
std,22.157879,18.313705,8.596906e+06,5.767840,2.195578e+06,6.508420,5.380459e+06,252.185786
min,61.000000,33.000000,8.500000e+02,3.000000,1.380000e+02,3.000000,2.760000e+02,4.000000
25%,115.000000,74.000000,6.831550e+04,13.000000,1.250925e+04,26.000000,2.239125e+04,219.000000
50%,123.000000,80.000000,5.205080e+05,16.000000,1.006500e+05,28.000000,1.884660e+05,432.000000
75%,137.750000,95.000000,2.111314e+06,16.000000,3.568158e+05,28.000000,6.307618e+05,645.250000
max,260.000000,189.000000,9.164621e+07,79.000000,2.242470e+07,90.000000,6.537774e+07,894.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 12 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 214 non-null    object
 1   combined figures (kg/capita/year)       214 non-null    int64
 2   Household estimate (kg/capita/year)     214 non-null    int64
 3   Household estimate (tonnes/year)        214 non-null    int64
 4   Retail estimate (kg/capita/year)        214 non-null    int64
 5   Retail estimate (tonnes/year)           214 non-null    int64
 6   Food service estimate (kg/capita/year)  214 non-null    int64
 7   Food service estimate (tonnes/year)     214 non-null    int64
 8   Confidence in estimate                  214 non-null    object
 9   M49 code                                214 non-null    int64
 10  Region                                  214 non-null    object
 11  Source                                  214 non-null    object
dtypes: int64(8), object(4)
memory usage: 20.2+ KB

In [7]:
df.head(5)

,Country,combined figures (kg/capita/year),Household estimate (kg/capita/year),Household estimate (tonnes/year),Retail estimate (kg/capita/year),Retail estimate (tonnes/year),Food service estimate (kg/capita/year),Food service estimate (tonnes/year),Confidence in estimate,M49 code,Region,Source
0,Afghanistan,126,82,3109153,16,594982,28,1051783,Very Low Confidence,4,Southern Asia,https://www.unep.org/resources/report/unep-foo...
1,Albania,127,83,238492,16,45058,28,79651,Very Low Confidence,8,Southern Europe,https://www.unep.org/resources/report/unep-foo...
2,Algeria,135,91,3918529,16,673360,28,1190335,Very Low Confidence,12,Northern Africa,https://www.unep.org/resources/report/unep-foo...
3,Andorra,123,84,6497,13,988,26,1971,Low Confidence,20,Southern Europe,https://www.unep.org/resources/report/unep-foo...
4,Angola,144,100,3169523,16,497755,28,879908,Very Low Confidence,24,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...

In [8]:
df.tail(5)

,Country,combined figures (kg/capita/year),Household estimate (kg/capita/year),Household estimate (tonnes/year),Retail estimate (kg/capita/year),Retail estimate (tonnes/year),Food service estimate (kg/capita/year),Food service estimate (tonnes/year),Confidence in estimate,M49 code,Region,Source
209,Venezuela (Boliv. Rep. of),116,72,2065461,16,445994,28,788407,Very Low Confidence,862,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
210,Viet Nam,120,76,7346717,16,1508689,28,2666991,Very Low Confidence,704,South-eastern Asia,https://www.unep.org/resources/report/unep-foo...
211,Yemen,148,104,3026946,16,456099,28,806270,Very Low Confidence,887,Western Asia,https://www.unep.org/resources/report/unep-foo...
212,Zambia,122,78,1391729,16,279350,28,493822,Very Low Confidence,894,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
213,Zimbabwe,144,100,1458564,16,229059,28,404920,Very Low Confidence,716,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...

In [9]:
new_df = df.dropna()

In [10]:
print(new_df)

                        Country  combined figures (kg/capita/year)  \
0                   Afghanistan                                126
1                       Albania                                127
2                       Algeria                                135
3                       Andorra                                123
4                        Angola                                144
..                          ...                                ...
209  Venezuela (Boliv. Rep. of)                                116
210                    Viet Nam                                120
211                       Yemen                                148
212                      Zambia                                122
213                    Zimbabwe                                144

     Household estimate (kg/capita/year)  Household estimate (tonnes/year)  \
0                                     82                           3109153
1                                     83                            238492
2                                     91                           3918529
3                                     84                              6497
4                                    100                           3169523
..                                   ...                               ...
209                                   72                           2065461
210                                   76                           7346717
211                                  104                           3026946
212                                   78                           1391729
213                                  100                           1458564

     Retail estimate (kg/capita/year)  Retail estimate (tonnes/year)  \
0                                  16                         594982
1                                  16                          45058
2                                  16                         673360
3                                  13                            988
4                                  16                         497755
..                                ...                            ...
209                                16                         445994
210                                16                        1508689
211                                16                         456099
212                                16                         279350
213                                16                         229059

     Food service estimate (kg/capita/year)  \
0                                        28
1                                        28
2                                        28
3                                        26
4                                        28
..                                      ...
209                                      28
210                                      28
211                                      28
212                                      28
213                                      28

     Food service estimate (tonnes/year) Confidence in estimate  M49 code  \
0                                1051783    Very Low Confidence         4
1                                  79651    Very Low Confidence         8
2                                1190335    Very Low Confidence        12
3                                   1971         Low Confidence        20
4                                 879908    Very Low Confidence        24
..                                   ...                    ...       ...
209                               788407    Very Low Confidence       862
210                              2666991    Very Low Confidence       704
211                               806270    Very Low Confidence       887
212                               493822    Very Low Confidence       894
213                               404920    Very Low Confidence       716

                              Region  \
0                      Southern Asia
1                    Southern Europe
2                    Northern Africa
3                    Southern Europe
4                 Sub-Saharan Africa
..                               ...
209  Latin America and the Caribbean
210               South-eastern Asia
211                     Western Asia
212               Sub-Saharan Africa
213               Sub-Saharan Africa

                                                Source
0    https://www.unep.org/resources/report/unep-foo...
1    https://www.unep.org/resources/report/unep-foo...
2    https://www.unep.org/resources/report/unep-foo...
3    https://www.unep.org/resources/report/unep-foo...
4    https://www.unep.org/resources/report/unep-foo...
..                                                 ...
209  https://www.unep.org/resources/report/unep-foo...
210  https://www.unep.org/resources/report/unep-foo...
211  https://www.unep.org/resources/report/unep-foo...
212  https://www.unep.org/resources/report/unep-foo...
213  https://www.unep.org/resources/report/unep-foo...

[214 rows x 12 columns]

In [11]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 12 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 214 non-null    object
 1   combined figures (kg/capita/year)       214 non-null    int64
 2   Household estimate (kg/capita/year)     214 non-null    int64
 3   Household estimate (tonnes/year)        214 non-null    int64
 4   Retail estimate (kg/capita/year)        214 non-null    int64
 5   Retail estimate (tonnes/year)           214 non-null    int64
 6   Food service estimate (kg/capita/year)  214 non-null    int64
 7   Food service estimate (tonnes/year)     214 non-null    int64
 8   Confidence in estimate                  214 non-null    object
 9   M49 code                                214 non-null    int64
 10  Region                                  214 non-null    object
 11  Source                                  214 non-null    object
dtypes: int64(8), object(4)
memory usage: 20.2+ KB

In [12]:
x = new_df["Food service estimate (tonnes/year)"].mean()

In [13]:
print(x)

1138859.2476635515

## Descriptive Analysis

In [15]:
import pandas as pd

# Load your dataset
df = pd.read_csv("food_waste.csv")

# Disable scientific notation for readability
pd.set_option('display.float_format', '{:.2f}'.format)

# 1. Basic structure
print("Shape of the dataset:", df.shape)
print("\nColumn names:", df.columns.tolist())

# 2. Summary statistics for all numeric columns
print("\n--- Summary Statistics ---")
print(df.describe())

# 3. Mean values for per capita waste
print("\n--- Average Per Capita Waste (kg/year) ---")
columns_of_interest = [
    'combined figures (kg/capita/year)',
    'Household estimate (kg/capita/year)',
    'Retail estimate (kg/capita/year)',
    'Food service estimate (kg/capita/year)'
]
print(df[columns_of_interest].mean())

# 4. Country with highest total household waste (tonnes)
highest_household = df.loc[df['Household estimate (tonnes/year)'].idxmax()]
print("\n--- Country with Highest Household Waste (tonnes) ---")
print(highest_household[['Country', 'Household estimate (tonnes/year)']])

# 5. Region-wise average per capita waste
print("\n--- Region-wise Average Per Capita Waste ---")
region_group = df.groupby('Region')[columns_of_interest].mean().sort_values(
    by='combined figures (kg/capita/year)', ascending=False)
print(region_group)

Shape of the dataset: (214, 12)

Column names: ['Country', 'combined figures (kg/capita/year)', 'Household estimate (kg/capita/year)', 'Household estimate (tonnes/year)', 'Retail estimate (kg/capita/year)', 'Retail estimate (tonnes/year)', 'Food service estimate (kg/capita/year)', 'Food service estimate (tonnes/year)', 'Confidence in estimate', 'M49 code', 'Region', 'Source']

--- Summary Statistics ---
       combined figures (kg/capita/year)  Household estimate (kg/capita/year)  \
count                             214.00                               214.00
mean                              126.79                                84.29
std                                22.16                                18.31
min                                61.00                                33.00
25%                               115.00                                74.00
50%                               123.00                                80.00
75%                               137.75                                95.00
max                               260.00                               189.00

       Household estimate (tonnes/year)  Retail estimate (kg/capita/year)  \
count                            214.00                            214.00
mean                         2658895.65                             15.12
std                          8596906.22                              5.77
min                              850.00                              3.00
25%                            68315.50                             13.00
50%                           520508.00                             16.00
75%                          2111314.50                             16.00
max                         91646213.00                             79.00

       Retail estimate (tonnes/year)  Food service estimate (kg/capita/year)  \
count                         214.00                                  214.00
mean                       552045.43                                   27.38
std                       2195578.49                                    6.51
min                           138.00                                    3.00
25%                         12509.25                                   26.00
50%                        100650.00                                   28.00
75%                        356815.75                                   28.00
max                      22424705.00                                   90.00

       Food service estimate (tonnes/year)  M49 code
count                               214.00    214.00
mean                            1138859.25    433.97
std                             5380459.14    252.19
min                                 276.00      4.00
25%                               22391.25    219.00
50%                              188466.00    432.00
75%                              630761.75    645.25
max                            65377741.00    894.00

--- Average Per Capita Waste (kg/year) ---
combined figures (kg/capita/year)        126.79
Household estimate (kg/capita/year)       84.29
Retail estimate (kg/capita/year)          15.12
Food service estimate (kg/capita/year)    27.38
dtype: float64

--- Country with Highest Household Waste (tonnes) ---
Country                                China
Household estimate (tonnes/year)    91646213
Name: 39, dtype: object

--- Region-wise Average Per Capita Waste ---
                                 combined figures (kg/capita/year)  \
Region
Sub-Saharan Africa                                          145.40
Western Asia                                                145.39
South-eastern Asia                                          137.45
Northern Africa                                             133.50
Central Asia                                                130.20
Melanesia                                                   128.60
Micronesia                                                  123.14
Southern Europe                                             123.00
Northern America                                            120.75
Polynesia                                                   119.50
Latin America and the Caribbean                             115.55
Southern Asia                                               113.11
Eastern Asia                                                113.00
Northern Europe                                             111.67
Australia and New Zealand                                   111.50
Eastern Europe                                              109.40
Western Europe                                              104.89

                                 Household estimate (kg/capita/year)  \
Region
Sub-Saharan Africa                                            101.65
Western Asia                                                  101.06
South-eastern Asia                                             83.00
Northern Africa                                                89.50
Central Asia                                                   86.20
Melanesia                                                      85.60
Micronesia                                                     82.00
Southern Europe                                                85.60
Northern America                                               71.50
Polynesia                                                      76.75
Latin America and the Caribbean                                73.57
Southern Asia                                                  71.89
Eastern Asia                                                   71.43
Northern Europe                                                74.67
Australia and New Zealand                                      81.50
Eastern Europe                                                 68.10
Western Europe                                                 67.11

                                 Retail estimate (kg/capita/year)  \
Region
Sub-Saharan Africa                                          15.77
Western Asia                                                17.17
South-eastern Asia                                          21.18
Northern Africa                                             16.00
Central Asia                                                16.00
Melanesia                                                   15.40
Micronesia                                                  14.29
Southern Europe                                             12.60
Northern America                                            13.75
Polynesia                                                   15.25
Latin America and the Caribbean                             14.79
Southern Asia                                               16.00
Eastern Asia                                                13.71
Northern Europe                                             12.83
Australia and New Zealand                                    6.00
Eastern Europe                                              14.30
Western Europe                                              12.00

                                 Food service estimate (kg/capita/year)
Region
Sub-Saharan Africa                                                27.98
Western Asia                                                      27.17
South-eastern Asia                                                33.27
Northern Africa                                                   28.00
Central Asia                                                      28.00
Melanesia                                                         27.60
Micronesia                                                        26.86
Southern Europe                                                   24.80
Northern America                                                  35.50
Polynesia                                                         27.50
Latin America and the Caribbean                                   27.19
Southern Asia                                                     25.22
Eastern Asia                                                      27.86
Northern Europe                                                   24.17
Australia and New Zealand                                         24.00
Eastern Europe                                                    27.00
Western Europe                                                    25.78